feat: add treasury pallet
polkafoundry/newpolka pull request #26
Opened 2021-05-10 10:31 UTC by haicon2321993

2021-05-10 15:28 UTC, thanhtung6824 requested changes

2021-05-10 15:28 UTC, thanhtung6824 commented on pallets/treasury/src/lib.rs
> +            let c = ProposalCount::<T>::get();
Do we really need it atm? Nothing proposed yet

2021-05-10 15:28 UTC, thanhtung6824 commented on pallets/treasury/src/tests.rs
> +fn init_reward_work() {
wrong name

2021-05-10 15:28 UTC, thanhtung6824 commented on pallets/treasury/src/lib.rs
> +            T::Currency::transfer(&Self::account_id(), &dest, amount, AllowDeath)
We should check the amount must be large than the minimum balance, just in case

2021-05-10 15:28 UTC, thanhtung6824 commented on pallets/treasury/src/lib.rs
> +            T::Currency::transfer(&sender, &Self::account_id(), amount, AllowDeath)
same upper

2021-05-10 15:28 UTC, thanhtung6824 commented on pallets/treasury/src/lib.rs
> +        /// Take funds from the Charity's pot and send them somewhere. This call requires root origin,
Treasury's pot

2021-05-10 15:28 UTC, thanhtung6824 commented on pallets/treasury/src/lib.rs
> +        /// Allocate the Charity's funds
Treasury's funds

2021-05-10 15:30 UTC, thanhtung6824 commented
As our discussion, please add more test for the crowdloan pallet

2021-05-11 02:57 UTC, thanhtung6824 requested changes

2021-05-11 02:57 UTC, thanhtung6824 commented on pallets/crowdloan-rewards/src/lib.rs
> +			T::Currency::transfer(
check T::Currency::minimum_balance in here as well

2021-05-11 04:27 UTC, haicon2321993 commented on pallets/treasury/src/lib.rs
> +            let c = ProposalCount::<T>::get();
Remove redundant code
https://github.com/polkafoundry/newpolka/pull/26/commits/48e10be2cad7b91c38e3000f78edb79048029d3e#diff-c73bb87d2ed2bae44d9606e67114943e2ce286d5ff083a012f0b766015b067fdL119

2021-05-11 04:28 UTC, haicon2321993 commented on pallets/treasury/src/tests.rs
> +fn init_reward_work() {
Remove and add more test case
https://github.com/polkafoundry/newpolka/pull/26/commits/0a5effd47b66866700bdd640e9b5d6feb23dc8d9#diff-acabb9b9ad616c45711d6902df79bd182dfc393accd523064fa3a77c5bf48944R6

2021-05-11 04:30 UTC, haicon2321993 commented on pallets/treasury/src/lib.rs
> +            T::Currency::transfer(&Self::account_id(), &dest, amount, AllowDeath)
Added
https://github.com/polkafoundry/newpolka/pull/26/commits/48e10be2cad7b91c38e3000f78edb79048029d3e#diff-c73bb87d2ed2bae44d9606e67114943e2ce286d5ff083a012f0b766015b067fdR86

2021-05-11 04:31 UTC, haicon2321993 commented on pallets/treasury/src/lib.rs
> +            T::Currency::transfer(&sender, &Self::account_id(), amount, AllowDeath)
Added
https://github.com/polkafoundry/newpolka/pull/26/commits/48e10be2cad7b91c38e3000f78edb79048029d3e#diff-c73bb87d2ed2bae44d9606e67114943e2ce286d5ff083a012f0b766015b067fdR86

2021-05-11 04:32 UTC, haicon2321993 commented on pallets/crowdloan-rewards/src/lib.rs
> +			T::Currency::transfer(
Add checking reward
https://github.com/polkafoundry/newpolka/pull/26/commits/0295c47d6742730fb15edb7c245f04c6fa779271#diff-2bbae40c9c7fdfeeb0b1708d368844303a595083bc948ccd684b577e5d13f6ebR189

2021-05-11 04:33 UTC, haicon2321993 commented
> As our discussion, please add more test for the crowdloan pallet

update our test cases to pass all logic
https://github.com/polkafoundry/newpolka/pull/26/commits/5668bf3561495d93290136a6e680f09befe9203c

2021-05-11 04:36 UTC, haicon2321993 commented on pallets/treasury/src/lib.rs
> +        /// Take funds from the Charity's pot and send them somewhere. This call requires root origin,
Changed it
https://github.com/polkafoundry/newpolka/pull/26/commits/b8c14ea50da590a07d14abb6e2f2b1f59f13c4bc

2021-05-11 04:37 UTC, haicon2321993 commented on pallets/treasury/src/lib.rs
> +        /// Allocate the Charity's funds
Chaned it
https://github.com/polkafoundry/newpolka/pull/26/commits/b8c14ea50da590a07d14abb6e2f2b1f59f13c4bc

2021-05-11 04:40 UTC, merged